038_KonuYorumCoreIntroBilgeAdam/Controllers/KonuController.cs
using _038_KonuYorumCoreIntroBilgeAdam.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _038_KonuYorumCoreIntroBilgeAdam.Controllers
{
    public class KonuController : Controller
    {
        private BA_KonuYorumCoreContext _db = new BA_KonuYorumCoreContext();

        public IActionResult Index()
        {
            List<Konu> konular = _db.Konu.ToList();
            return View(konular);
        }

        public IActionResult Details(int id)
        {
            Konu konu = _db.Konu.Find(id);
            return View(konu);
        }

        [HttpGet] // Eğer yazılmazsa default olarak her aksiyon HttpGet'tir
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // sunucuya bir form veya başka bir yol ile veri gönderiliyorsa mutlaka HttpPost yazılmalıdır
        public IActionResult Create(Konu konu)
        {
            if (string.IsNullOrWhiteSpace(konu.Baslik))
            {
                // ViewBag (özellik) ile ViewData (index) birbirleri yerine aynı özellik ve index adları üzerinden kullanılabilir 

                //ViewData["Mesaj"] = "Başlık boş girilemez!";
                ViewBag.Mesaj = "Başlık boş girilemez!";

                return View(konu);
            }
            if (konu.Baslik.Length > 100)
            {
                ViewBag.Mesaj = "Başlık en fazla 100 karakter olmalıdır!";
                return View(konu);
            }
            if (!string.IsNullOrWhiteSpace(konu.Aciklama) && konu.Aciklama.Length > 200)
            {
                ViewBag.Mesaj = "Açıklama en fazla 200 karakter olmalıdır!";
                return View(konu);
            }

            _db.Konu.Add(konu);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet] // Eğer yazılmazsa default olarak her aksiyon HttpGet'tir
        public IActionResult Edit(int id)
        {
            //Konu konu = _db.Konu.Find(id);

            //Konu konu = _db.Konu.First(konu => konu.Id == id); // eğer belirtilen koşula uygun sonuç dönmezse exception fırlatır, eğer belirtilen koşula uygun birden çok kayıt dönerse de her zaman ilk kaydı döner

            //Konu konu = _db.Konu.FirstOrDefault(konu => konu.Id == id); // eğer belirtilen koşula uygun sonuç dönmezse null döner, eğer belirtilen koşula uygun birden çok kayıt dönerse de her zaman ilk kaydı döner

            // Last, eğer belirtilen koşula uygun sonuç dönmezse hata fırlatır, eğer belirtilen koşula uygun birden çok kayıt dönerse de her zaman son kaydı döner

            // LastOrDefault, eğer belirtilen koşula uygun sonuç dönmezse null döner, eğer belirtilen koşula uygun birden çok kayıt dönerse de her zaman son kaydı döner

            //Konu konu = _db.Konu.Single(konu => konu.Id == id); // eğer belirtilen koşula uygun sonuç dönmezse exception fırlatır, eğer belirtilen koşula uygun birden çok kayıt dönerse de exception fırlatır

            Konu konu = _db.Konu.SingleOrDefault(konu => konu.Id == id); // eğer belirtilen koşula uygun sonuç dönmezse null döner, eğer belirtilen koşula uygun birden çok kayıt dönerse de exception fırlatır

            // eğer expression olarak birden çok koşul kullanılmak isteniyorsa bu koşullar and (&&) veya or (||) ile birleştirilebilir, değil işlemi için de not (!) kullanılabilir

            return View(konu);
        }

        [HttpPost] // sunucuya bir form veya başka bir yol ile veri gönderiliyorsa mutlaka HttpPost yazılmalıdır
        public IActionResult Edit(Konu konu)
        {
            if (string.IsNullOrWhiteSpace(konu.Baslik))
            {
                ViewData["Mesaj"] = "Başlık boş girilemez!";
                return View(konu);
            }
            if (konu.Baslik.Length > 100)
            {
                ViewBag.Mesaj = "Başlık en fazla 100 karakter olmalıdır!";
                return View(konu);
            }
            if (!string.IsNullOrWhiteSpace(konu.Aciklama) && konu.Aciklama.Length > 200)
            {
                ViewBag.Mesaj = "Açıklama en fazla 200 karakter olmalıdır!";
                return View(konu);
            }

            // güncelleme ve silme işlemleri için veri önce mutlaka veritabanındaki tablodan çekilmelidir ve sonra çekilen obje üzerinden güncelleme veya silme yapılmalıdır.
            Konu mevcutKonu = _db.Konu.SingleOrDefault(mevcutKonu => mevcutKonu.Id == konu.Id);
            mevcutKonu.Baslik = konu.Baslik;
            mevcutKonu.Aciklama = konu.Aciklama;
            _db.Konu.Update(mevcutKonu);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            // konu verileriyle birlikte Include kullanarak ilişkili yorum verileri de çekilir.
            // eager loading: ihtiyaca göre yükleme, Entity Framework Core'da kullanılır.
            // lazy loading: entity framework'ün otomatik olarak ilişkili verileri yüklemesi, Include kullanılmasına gerek yoktur.
            // güncelleme ve silme işlemleri için veri önce mutlaka veritabanındaki tablodan çekilmelidir ve sonra çekilen obje üzerinden güncelleme veya silme yapılmalıdır.
            Konu konu = _db.Konu.Include(k => k.Yorum).SingleOrDefault(k => k.Id == id);

            // 1. yöntem: konu ile birlikte ilişkili yorum kayıtlarının da silinmesi:
            //if (konu.Yorum != null && konu.Yorum.Count > 0) // yorum kayıtları doluysa
            //{
            //    foreach (Yorum yorum in konu.Yorum)
            //    {
            //        _db.Yorum.Remove(yorum);
            //    }
            //}
            //_db.Yorum.RemoveRange(konu.Yorum);

            // 2. yöntem: konunun ilişkili yorum kayıtları varsa uyarı verilmesi ve silinme işleminin yapılmaması:
            if (konu.Yorum != null && konu.Yorum.Count > 0)
            {
                // Eğer view dönmek yerine başka bir aksiyona yönlendirme yapılıyorsa TempData ile veriler yönlendirilen aksiyonun view'ına taşınmalıdır
                TempData["Mesaj"] = "Silinmek istenen konu ile ilişkili yorum kayıtları bulunmaktadır!";
            }
            else
            {
                _db.Konu.Remove(konu);
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

038_KonuYorumCoreIntroBilgeAdam/Controllers/KonuScaffoldingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _038_KonuYorumCoreIntroBilgeAdam.DataAccess;

namespace _038_KonuYorumCoreIntroBilgeAdam.Controllers
{
    public class KonuScaffoldingController : Controller
    {
        private readonly BA_KonuYorumCoreContext _context;

        //public KonuScaffoldingController(BA_KonuYorumCoreContext context)
        //{
        //    _context = context;
        //}

        public KonuScaffoldingController()
        {
            _context = new BA_KonuYorumCoreContext();
        }

        // GET: KonuScaffolding
        public IActionResult Index()
        {
            return View(_context.Konu.ToList());
        }

        // GET: KonuScaffolding/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var konu = _context.Konu
                .SingleOrDefault(m => m.Id == id);
            if (konu == null)
            {
                return NotFound();
            }

            return View(konu);
        }

        // GET: KonuScaffolding/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: KonuScaffolding/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Konu konu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(konu);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(konu);
        }

        // GET: KonuScaffolding/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var konu = _context.Konu.Find(id);
            if (konu == null)
            {
                return NotFound();
            }
            return View(konu);
        }

        // POST: KonuScaffolding/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Konu konu)
        {
            if (ModelState.IsValid)
            {
                _context.Update(konu);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(konu);
        }

        // GET: KonuScaffolding/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var konu = _context.Konu
                .SingleOrDefault(m => m.Id == id);
            if (konu == null)
            {
                return NotFound();
            }

            return View(konu);
        }

        // POST: KonuScaffolding/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var konu = _context.Konu.Find(id);
            _context.Konu.Remove(konu);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
	}
}

038_KonuYorumCoreIntroBilgeAdam/Controllers/YorumController.cs
using _038_KonuYorumCoreIntroBilgeAdam.DataAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace _038_KonuYorumCoreIntroBilgeAdam.Controllers
{
    public class YorumController : Controller
    {
        private BA_KonuYorumCoreContext _db = new BA_KonuYorumCoreContext();

        public IActionResult Index()
        {
            // select * from Yorum order by Puan desc
            //List<Yorum> yorumlar = _db.Yorum.OrderByDescending(yorum => yorum.Puan).ToList(); // OrderBy, OrderByDescending
            // Bu şekilde ilişkili Konu kayıtları boş gelir.

            // select * from Yorum left outer join Konu on Yorum.KonuId = Konu.Id order by Puan desc, Yorumcu
            List<Yorum> yorumlar = _db.Yorum.Include(yorum => yorum.Konu).OrderByDescending(yorum => yorum.Puan).ThenBy(yorum => yorum.Yorumcu).ToList(); // ThenBy, ThenByDescending

            // Bir OrderBy kullanıldıktan sonra diğerlerinin hepsi ThenBy olmalıdır.

            return View(yorumlar);
        }

        public IActionResult Details(int id)
        {
            Yorum yorum = _db.Yorum.Include(yorum => yorum.Konu).SingleOrDefault(yorum => yorum.Id == id);
            return View(yorum);
        }

        public IActionResult Create()
        {
            List<Konu> konular = _db.Konu.OrderBy(konu => konu.Baslik).ToList();

            //ViewBag.KonuId = new SelectList(konular, "Id", "Baslik");
            ViewData["KonuId"] = new SelectList(konular, "Id", "Baslik"); // SelectList -> DropDownList, MultiSelectList -> ListBox

            return View();
        }

        [HttpPost]
        public IActionResult Create(Yorum yorum)
        {
            if (string.IsNullOrWhiteSpace(yorum.Icerik))
            {
                ViewBag.Mesaj = "İçerik boş girilemez!";
                ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(k => k.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
                return View(yorum);
            }
            if (yorum.Icerik.Length > 500)
            {
                ViewBag.Mesaj = "İçerik en fazla 500 karakter olmalıdır!";
                ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(k => k.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
                return View(yorum);
            }
            if (string.IsNullOrWhiteSpace(yorum.Yorumcu))
            {
                ViewBag.Mesaj = "Yorumcu boş girilemez!";
                ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(k => k.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
                return View(yorum);
            }
            if (yorum.Yorumcu.Length > 50)
            {
                ViewBag.Mesaj = "Yorumcu en fazla 50 karakter olmalıdır!";
                ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(k => k.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
                return View(yorum);
            }

            //if (yorum.Puan != null)
            if (yorum.Puan.HasValue)
            {
                //if (yorum.Puan.Value > 5 || yorum.Puan.Value < 1)
                if (!(yorum.Puan.Value >= 1 && yorum.Puan.Value <= 5))
                {
                    ViewBag.Mesaj = "Puan 1 ile 5 arasında olmalıdır!";
                    ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(k => k.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
                    return View(yorum);
                }
            }

            _db.Yorum.Add(yorum);
            _db.SaveChanges();
            TempData["YorumMesaj"] = "Yorum başarıyla eklendi.";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Yorum yorum = _db.Yorum.SingleOrDefault(yorum => yorum.Id == id);
            ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(konu => konu.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
            return View(yorum);
        }

        [HttpPost]
        public IActionResult Edit(Yorum yorum)
        {
            if (string.IsNullOrWhiteSpace(yorum.Icerik))
            {
                ViewBag.Mesaj = "İçerik boş girilemez!";
                ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(k => k.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
                return View(yorum);
            }
            if (yorum.Icerik.Length > 500)
            {
                ViewBag.Mesaj = "İçerik en fazla 500 karakter olmalıdır!";
                ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(k => k.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
                return View(yorum);
            }
            if (string.IsNullOrWhiteSpace(yorum.Yorumcu))
            {
                ViewBag.Mesaj = "Yorumcu boş girilemez!";
                ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(k => k.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
                return View(yorum);
            }
            if (yorum.Yorumcu.Length > 50)
            {
                ViewBag.Mesaj = "Yorumcu en fazla 50 karakter olmalıdır!";
                ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(k => k.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
                return View(yorum);
            }
            if (yorum.Puan.HasValue)
            {
                if (!(yorum.Puan.Value >= 1 && yorum.Puan.Value <= 5))
                {
                    ViewBag.Mesaj = "Puan 1 ile 5 arasında olmalıdır!";
                    ViewBag.KonuId = new SelectList(_db.Konu.OrderBy(k => k.Baslik).ToList(), "Id", "Baslik", yorum.KonuId);
                    return View(yorum);
                }
            }

            Yorum mevcutYorum = _db.Yorum.SingleOrDefault(mevcutYorum => mevcutYorum.Id == yorum.Id);
            mevcutYorum.Icerik = yorum.Icerik;
            mevcutYorum.Yorumcu = yorum.Yorumcu;
            mevcutYorum.Puan = yorum.Puan;
            mevcutYorum.KonuId = yorum.KonuId;
            _db.Yorum.Update(mevcutYorum);
            _db.SaveChanges();
            TempData["YorumMesaj"] = "Yorum başarıyla güncellendi.";
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id) // ~/Yorum/Delete/1
        {
            Yorum yorum = _db.Yorum.Include(yorum => yorum.Konu).SingleOrDefault(yorum => yorum.Id == id);
            return View(yorum);
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id) // ~/Yorum/Delete
        {
            Yorum yorum = _db.Yorum.Find(id);
            _db.Yorum.Remove(yorum);
            _db.SaveChanges();
            TempData["YorumMesaj"] = "Yorum başarıyla silindi.";
            return RedirectToAction("Index");
        }
    }
}

038_KonuYorumCoreIntroBilgeAdam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _038_KonuYorumCoreIntroBilgeAdam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_038_KonuYorumCoreIntroBilgeAdam.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_038_KonuYorumCoreIntroBilgeAdam</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@

                        @* Yukarıdaki menüdeki konu listesini getirmek için Konular bağlantısı (link'i) *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Konu" asp-action="Index">Konular</a>
                        </li>

                        @* Yukarıdaki menüdeki yorum listesini getirmek için Yorumlar bağlantısı (link'i) *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Yorum" asp-action="Index">Yorumlar</a>
                        </li>

                         @* Yukarıdaki menüdeki scaffold edilmiş konu listesini getirmek için Konular bağlantısı (link'i) *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="KonuScaffolding" asp-action="Index">Konular (Scaffolding)</a>
                        </li>

                         @* Yukarıdaki menüdeki scaffold edilmiş yorum listesini getirmek için Yorumlar bağlantısı (link'i) *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="YorumScaffolding" asp-action="Index">Yorumlar (Scaffolding)</a>
                        </li>

                         @* Yukarıdaki menüdeki konu ile inner join'lenmiş yorum listesini getirmek için KonularYorumlarJoin bağlantısı (link'i) *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="KonularYorumlarJoin" asp-action="InnerJoin">Konular Yorumlar Inner Join</a>
                        </li>

                        @* Yukarıdaki menüdeki konu ile left outer join'lenmiş yorum listesini getirmek için KonularYorumlarJoin bağlantısı (link'i) *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="KonularYorumlarJoin" asp-action="LeftOuterJoin">Konular Yorumlar Left Outer Join</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - _038_KonuYorumCoreIntroBilgeAdam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>